from tkinter import *
win = Tk()
win.title("Grid Test Example")
win.resizable(0,0)
Label(win,text="USERNAME: ").grid(column=0,row=0,sticky='e')
Entry(win,width=30).grid(column=1,row=0,sticky='we',pady=5,columnspan=9)
Label(win,text="PASSWORD: ").grid(column=0,row=1,sticky='e')
Entry(win,width=30).grid(column=1,row=1,sticky='we',pady=5,columnspan=9)
Button(win,text="Find",width=10).grid(row=0,column=10,sticky='e'+'w',pady=2,padx=2)
Button(win,text="Find All",width=10).grid(row=1,column=10,sticky='e'+'w',pady=2,padx=2)
Button(win,text="Replace",width=10).grid(row=2,column=10,sticky='e'+'w',pady=2,padx=2)
Button(win,text="Replace All",width=10).grid(row=3,column=10,sticky='e'+'w',pady=2,padx=2)
Checkbutton(win,text="LED One").grid(row=2,column=2,sticky='w')
Checkbutton(win,text="LED Two").grid(row=2,column=3,sticky='w')
Checkbutton(win,text="LED Three").grid(row=2,column=4,sticky='w')
Radiobutton(win,text="UP",value=1).grid(row =3,column=2,sticky='w')
Radiobutton(win,text="DOWN",value=2).grid(row =3,column=3,sticky='w')
Radiobutton(win,text="SELECT",value=3).grid(row =3,column=4,sticky='w')
win.mainloop()

