from tkinter import *
win = Tk()
win.title("Windows Form")
Label(win,text="Tkinter pack() Example:").pack()
frame = Frame(win)
Button(frame,text='A').pack(side=LEFT,fill=Y)
Button(frame,text='B').pack(side=TOP,fill=X)
Button(frame,text='C').pack(side=RIGHT)
Button(frame,text='D').pack(side=TOP)
frame.pack()
Label(win,text="Tkinter pack() Normal:").pack()
Button(win,text="Button").pack()
Button(win,text="Button").pack()
Button(win,text="Button").pack(side=LEFT,padx=2,pady=2,expand=1)
Button(win,text="Button").pack(side=LEFT,padx=2,expand=1)
Button(win,text="Button").pack(side=LEFT,padx=2,expand=1)
win.mainloop()
